apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: production
data:
  nats-server.conf: |
    pid_file: "/var/run/nats/nats.pid"
    http: 8222
    server_name: "$REGION-$POD_NAME"

    jetstream: enabled

    max_payload: 25MB

    websocket {
      port: 8080
      no_tls: true
    }

    authorization {
      token: "$NATSTOKEN"
    }

    cluster {
      name: "$REGION"
      listen: "0.0.0.0:6222"

      routes = [
        nats://nats-0.nats:6222
        nats://nats-1.nats:6222
        nats://nats-2.nats:6222
      ]

      connect_retries: 30
    }

    gateway {
      name: "$REGION"
      listen: "0.0.0.0:7222"
      connect_retries: 30
      advertise: "$PODIP:7222"
      gateways: [
          { 
            "name": "us-east1", 
            "urls": [ 
              "nats://nats-0.nats.$NS.svc.us-east1:7222",
              "nats://nats-1.nats.$NS.svc.us-east1:7222",
              "nats://nats-2.nats.$NS.svc.us-east1:7222"
            ]
          },
          {
            "name": "us-central1",
            "urls": [
              "nats://nats-0.nats.$NS.svc.us-central1:7222",
              "nats://nats-1.nats.$NS.svc.us-central1:7222",
              "nats://nats-2.nats.$NS.svc.us-central1:7222"
            ]
          },
          {
            "name": "us-south1",
            "urls": [
              "nats://nats-0.nats.$NS.svc.us-south1:7222",
              "nats://nats-1.nats.$NS.svc.us-south1:7222",
              "nats://nats-2.nats.$NS.svc.us-south1:7222"
            ]
          }
        ]
      }
    }