apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
  namespace: production
  labels:
    app: nats
spec:
  selector:
    matchLabels:
      app: nats
  replicas: 3
  serviceName: "nats"
  template:
    metadata:
      labels:
        app: nats
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
        - name: config-template
          configMap:
            name: nats-config
        - name: config
          emptyDir: {}
        - name: pid
          emptyDir: {}
      initContainers:
        - name: config-generator
          image: bhgedigital/envsubst:latest
          env:
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NS
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NATSTOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: key
            - name: PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: ["/bin/sh", "-c"]
          args:
            - |
              envsubst < /etc/nats-template/nats-server.conf > /etc/nats/nats-server.conf
          volumeMounts:
            - name: config-template
              mountPath: /etc/nats-template
            - name: config
              mountPath: /etc/nats
      containers:
        - name: nats-exporter
          image: natsio/prometheus-nats-exporter:latest
          args:
            - -varz
            - -use_internal_server_id
            - http://localhost:8222/
          ports:
            - containerPort: 7777
              name: metrics
          imagePullPolicy: Always
        - name: nats
          image: nats:alpine
          resources:
            requests:
              cpu: 50m
          ports:
            - containerPort: 4222
              name: client
              hostPort: 4222
            - containerPort: 7422
              name: leafnodes
              hostPort: 7422
            - containerPort: 6222
              name: cluster
            - containerPort: 8222
              name: monitor
            - containerPort: 8080
              name: ws
          volumeMounts:
            - name: config
              mountPath: /etc/nats
            - name: pid
              mountPath: /var/run/nats
          livenessProbe:
            httpGet:
              path: /
              port: 8222
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8222
            initialDelaySeconds: 10
            timeoutSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/nats-server -sl=ldm=/var/run/nats/nats.pid && /bin/sleep 60"]
          imagePullPolicy: Always