apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: asterisk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ast
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90