kind: ConfigMap
metadata:
  name: prometheus-gke
  namespace: production
apiVersion: v1
data:
  config.yaml: |
    global:
      scrape_interval: 60s
    scrape_configs:
    - job_name: fs
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: fs
    - job_name: asterisk
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: asterisk
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(asterisk_active_user_calls)"
        action: drop
    - job_name: mysql1
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: mysql
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(mysql_global_status_connections|mysql_global_status_opened_files|mysql_global_status_queries|mysql_global_status_threads_connected|mysql_global_status_threads_running|mysql_global_status_uptime|mysql_slave_status_slave_io_running|mysql_slave_status_slave_sql_running|mysql_up)"
        action: keep
    - job_name: mysql2
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: mysql
      metric_relabel_configs:
      - source_labels: [command]
        regex: "(insert|delete|select|update)"
        action: keep
    - job_name: proxysql
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: proxysql
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(proxysql_server_connections_connected|proxysql_client_connections_connected|proxysql_connpool_conns_queries_total|proxysql_questions_total|proxysql_connpool_conns)"
        action: keep
    - job_name: kamailio
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: kamailio
    - job_name: nats
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: nats
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(gnatsd_varz_cluster_name|gnatsd_varz_connections|gnatsd_varz_cpu|gnatsd_varz_gateway_name|gnatsd_varz_in_bytes|gnatsd_varz_out_bytes|gnatsd_varz_in_msgs|gnatsd_varz_out_msgs|gnatsd_varz_max_connections|gnatsd_varz_mem|gnatsd_varz_routes|gnatsd_varz_server_id|gnatsd_varz_subscriptions|gnatsd_varz_total_connections)"
        action: keep
    - job_name: rtpengine
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: rtpengine
    - job_name: integrations/kubernetes/kube-state-metrics
      kubernetes_sd_configs:
      - role: pod
      metric_relabel_configs:
      - source_labels: [__name__]
        regex: "(kube_horizontalpodautoscaler_status_desired_replicas|kube_horizontalpodautoscaler_status_current_replicas|kube_horizontalpodautoscaler_spec_max_replicas|kube_horizontalpodautoscaler_spec_min_replicas|kube_horizontalpodautoscaler_spec_target_metric|kube_horizontalpodautoscaler_status_target_metric)"
        action: keep
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: kube-state-metrics