apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs
  namespace: production
  labels:
    component: jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      component: jobs
  template:
    metadata:
      labels:
        component: jobs
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      volumes:
        - name: google-service-account
          secret:
            secretName: google-service-account
      containers:
        - name: jobs
          image: us-docker.pkg.dev/voxo-5060/voxoco/jobs:latest
          resources:
            requests:
              cpu: 700m
          volumeMounts:
            - name: google-service-account
              mountPath: /var/secrets/google
          env:
            - name: TZ
              value: America/Chicago
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: NATSSERVERS
              value: "nats://nats-svc:4222"
            - name: NATSTOKEN
              valueFrom:
                secretKeyRef:
                  name: nats-token
                  key: key
            - name: MYSQL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred