apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxysql
  namespace: production
  labels:
    component: proxysql
spec:
  replicas: 3
  selector:
    matchLabels:
      component: proxysql
  template:
    metadata:
      labels:
        component: proxysql
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: proxysql
          image: proxysql/proxysql
          ports:
            - name: proxysql
              containerPort: 6033
            - name: metrics
              containerPort: 6070
          resources:
            requests:
              cpu: 50m
        - name: sidecar
          image: alpine/mysql
          command: ["/bin/sh", "/scripts/proxysql.sh"]
          volumeMounts:
            - name: bootstrap-script
              mountPath: /scripts
          env:
            - name: MYSQL_PRIMARY_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-primary-url
                  key: key
            - name: MYSQL_READER_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-reader-url
                  key: key
            - name: DEBUG
              value: "0"
            - name: DB_NAME
              value: main
            - name: CLUSTER_NAME
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
          startupProbe:
            timeoutSeconds: 5
            failureThreshold: 20
            exec:
              command: ["cat", "/ready.txt"]
          imagePullPolicy: Always
      volumes:
        - name: bootstrap-script
          configMap:
            name: proxysql-bootstrap
            defaultMode: 0755
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - external-rtp
                - external-sip