apiVersion: batch/v1
kind: CronJob
metadata:
  name: hpa-scale-up
  namespace: production
spec:
  schedule: "45 6 * * 1-5"
  timeZone: "America/Chicago"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: manager
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - kubectl
            - patch
            - hpa/asterisk
            - -n
            - production
            - --type=merge
            - -p
            - '{"spec":{"minReplicas":2}}'
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hpa-scale-down
  namespace: production
spec:
  schedule: "0 10 * * 1-5"
  timeZone: "America/Chicago"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: manager
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - kubectl
            - patch
            - hpa/asterisk
            - -n
            - production
            - --type=merge
            - -p
            - '{"spec":{"minReplicas":1}}'
          restartPolicy: OnFailure
