apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: kamailio-mcs
  namespace: production
  labels:
    component: kamailio
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"8080":"webrtc-kamailio"}}'
spec:
  template:
    spec:
      selector:
        component: kamailio
      ports:
        - name: webrtc
          protocol: TCP
          port: 8080
          targetPort: 8080
        - name: tcp
          protocol: TCP
          port: 5065
          targetPort: 5065
  clusters:
  - link: "us-central1-b/us-central1"
  - link: "us-east1-b/us-east1"
  - link: "us-south1-b/us-south1"
---
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: omnia-api-mcs
  namespace: production
  annotations:
    cloud.google.com/backend-config: '{"ports": {"3031":"socket-api", "3030":"api"}}'
spec:
  template:
    spec:
      selector:
        component: omnia-api
      ports:
        - name: rest
          protocol: TCP
          port: 3030
        - name: socket
          protocol: TCP
          port: 3031
  clusters:
  - link: "us-central1-b/us-central1"
  - link: "us-east1-b/us-east1"
  - link: "us-south1-b/us-south1"

---

apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: voxo-api-mcs
  namespace: production
  annotations:
    cloud.google.com/backend-config: '{"ports": {"3050":"voxo-api"}}'
spec:
  template:
    spec:
      selector:
        component: voxo-api
      ports:
        - name: rest
          protocol: TCP
          port: 3050
  clusters:
  - link: "us-central1-b/us-central1"
  - link: "us-east1-b/us-east1"
  - link: "us-south1-b/us-south1"
