apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs
  namespace: production
  labels:
    component: fs
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fs
  template:
    metadata:
      labels:
        component: fs
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: freeswitch
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 21600
      volumes:
        - name: cache
          emptyDir: {}
        - name: google-service-account
          secret:
            secretName: google-service-account
        - name: media
          emptyDir:
            medium: Memory
            sizeLimit: "1Gi"
        - name: recordings
          emptyDir:
            medium: Memory
            sizeLimit: "1Gi"
      initContainers:
        - name: init
          image: us-docker.pkg.dev/voxo-5060/voxoco/voxo-telecom:latest
          volumeMounts:
            - name: google-service-account
              mountPath: /var/secrets/google
          imagePullPolicy: Always
          args:
            - --assign-external-ip=true
            - --region=$(REGION)
            - --zone=$(ZONE)
            - --node-name=$(NODE_NAME)
            - --type=media
          env:
            - name: SERVICE
              value: kube-client
            - name: NODE_ENV
              value: production
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: SERVERIDENV
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: SERVERID
              value: "9$(SERVERIDENV)"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: ZONE
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: zone
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      containers:
        - name: freeswitch
          image: us-docker.pkg.dev/voxo-5060/voxoco/freeswitch:latest
          ports:
            - containerPort: 8021
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "infinity"]
          resources:
            requests:
              cpu: 2500m
          env:
            - name: TZ
              value: America/Chicago
          volumeMounts:
            - name: media
              mountPath: /tmp/media
            - name: recordings
              mountPath: /tmp/recordings
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
              - NET_ADMIN
              - SYS_NICE
        - name: sidecar
          image: us-docker.pkg.dev/voxo-5060/voxoco/voxo-telecom:latest
          ports:
            - name: metrics
              containerPort: 3000
          env:
            - name: SERVICE
              value: freeswitch
            - name: TZ
              value: America/Chicago
            - name: NODE_ENV
              value: production
            - name: MYSQL_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-url
                  key: connectionString
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: clusterName
            - name: SERVERIDENV
              valueFrom:
                configMapKeyRef:
                  name: cluster-details
                  key: serverId
            - name: SERVERID
              value: "9$(SERVERIDENV)"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
          volumeMounts:
            - name: cache
              mountPath: /tmp/cache
            - name: google-service-account
              mountPath: /var/secrets/google
            - name: media
              mountPath: /tmp/media
            - name: recordings
              mountPath: /tmp/recordings
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred