apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: production
spec:
  acme:
    email: admin@voxo.co
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: voxo-5060
            serviceAccountSecretRef:
              name: google-service-account
              key: key.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sip-voxo-co
  namespace: production
spec:
  secretName: sip-voxo-co-tls
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
    - sip.voxo.co
  duration: 2160h
  renewBefore: 720h
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 2048
